events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    upstream frontend {
        server frontend:5173;
    }

    upstream backend {
        server api:8000;
    }

    upstream minio {
        server minio:9000;
    }

    server {
        listen 80;

        # Allows up to 500MB uploads for video files
        client_max_body_size 500M;

        # Frontend
        location / {
            proxy_pass http://frontend;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "Upgrade";
            proxy_set_header Host $host;
        }

        # Backend API
        location /api/ {
            proxy_pass http://backend/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        # MinIO Video Stream
        location /crux-videos/ {
            proxy_pass http://minio/crux-videos/;
            proxy_set_header Host minio:9000;
        }
    }
}
